### ISSUE TITLE
Asking for permission to use fmlock.

### ISSUE THREAD

**Issue by kokoko3k** [datenwolf/fmlock#1]
Hi, i develop gopreload:
https://github.com/kokoko3k/gopreload

...it is mainly a bash script, but uses some c code to map files into memory.
My c code does the same as your fmlock tool, but i'm not a c programmer, so i ask you if i can use your code (which is better) instead of mine.

Thanks.

**Comment by datenwolf** [comment]
Go ahead.

It's licensed under liberal OSI approved terms, why do you even ask? ;)

**Comment by kokoko3k** [comment]
Well, i'm not pratical about licensing issues, i just read the following:
"\* Neither the name of fmlock nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission."

So i asked.
Thanks!
