### ISSUE TITLE
fmlock on Debian

### ISSUE THREAD

**Issue by antistress** [datenwolf/fmlock#2]
Hi,

I tried to use GOPreload [1] on my Debian system. GOPreload is based on fmlock.

GOPreload author is using arch and GOPreload works fine on it as it seems to work also on gentoo.

But It doesn't seem to have any effect on my Debian system.

Therefore I'm wondering if fmlock has the right to lock memory on Debian or if there could be anything Debian-specific about it ? Maybe you could know something about it ?

BTW Memlockd seems to do the same job as fmlock (?), and Memlockd is packaged on Debian [2] therefore I tend to consider that fmlock is supposed to run on debian ?

Besides, is it normal that when I preload firefox with GOPreload preparing 137MB of files, fmlock still uses 0K RAM ?

$ pgrep fmlock
1888
$ pmap 1888
1888: /usr/share/gopreload/bin/fmlock.gopreload/tmp/preloadlist.txt
total 0K

Thanks in advance for your help !

Cheers

antistress

[1] https://github.com/kokoko3k/gopreload
[2] https://packages.debian.org/sid/memlockd | This seems to be a Russell Coker's project https://doc.coker.com.au/category/projects/

**Comment by datenwolf** [comment]
> Therefore I'm wondering if fmlock has the right to lock memory on Debian or if there could be anything Debian-specific about it ?

I don't think so. As a matter of fact I did develop fmlock on a Debian system (although I primarily use Gentoo)

> Maybe you could know something about it ?

My best guess is, that maybe some resource limit gets applied. I never thought of fmlock to be used on executables. Of course it should work with such as well. I wrote fmlock as a quick hack to keep a large-ish (~30GB) dataset in a workstation's RAM, so that between other things I had to do, when returning to that I'd not take another 5 minutes just to read it from HDD.

I'll have to look into it.

**Comment by kokoko3k** [comment]
Hi, since i modified fmlock a little, i'd test the one shipped with gopreload that way; as root:

```
# dd if=/dev/zero of=/tmp/zero bs=1M count=100
# find /tmp/zero >/tmp/out
# /usr/share/gopreload/bin/fmlock.gopreload /tmp/out &
# pmap $(pidof fmlock.gopreload)

```

my output on Arch is right, see that "zero" is locked

```
26862:   /usr/share/gopreload/bin/fmlock.gopreload /tmp/out
000055fb6bf35000      8K r-x-- fmlock.gopreload
000055fb6c136000      4K r---- fmlock.gopreload
000055fb6c137000      4K rw--- fmlock.gopreload
000055fb6dda7000    132K rw---   [ anon ]
00007f605c1e1000 102400K r--s- zero
00007f60625e1000   1632K r-x-- libc-2.23.so
00007f6062779000   2044K ----- libc-2.23.so
00007f6062978000     16K r---- libc-2.23.so
00007f606297c000      8K rw--- libc-2.23.so
00007f606297e000     16K rw---   [ anon ]
00007f6062982000    140K r-x-- ld-2.23.so
00007f6062b41000     12K rw---   [ anon ]
00007f6062ba5000      4K r---- ld-2.23.so
00007f6062ba6000      4K rw--- ld-2.23.so
00007f6062ba7000      4K rw---   [ anon ]
00007ffc6544c000    132K rw---   [ stack ]
00007ffc65522000     12K r----   [ anon ]
00007ffc65525000      8K r-x--   [ anon ]
ffffffffff600000      4K r-x--   [ anon ]
```

```
# killall fmlock.gopreload ; rm /tmp/zero /tmp/out
```

**Comment by antistress** [comment]
Hi,
Here what I get, which also seems correct :

```
# pmap $(pidof fmlock.gopreload)
2848:   /usr/share/gopreload/bin/fmlock.gopreload /tmp/out
0000000000400000      8K r-x-- fmlock.gopreload
0000000000601000      4K rw--- fmlock.gopreload
00000000007fe000    132K rw---   [ anon ]
00007fc121d20000 102400K r--s- zero
00007fc128120000   1672K r-x-- libc-2.19.so
00007fc1282c2000   2044K ----- libc-2.19.so
00007fc1284c1000     16K r---- libc-2.19.so
00007fc1284c5000      8K rw--- libc-2.19.so
00007fc1284c7000     16K rw---   [ anon ]
00007fc1284cb000    128K r-x-- ld-2.19.so
00007fc1286ca000     12K rw---   [ anon ]
00007fc1286e8000     12K rw---   [ anon ]
00007fc1286eb000      4K r---- ld-2.19.so
00007fc1286ec000      4K rw--- ld-2.19.so
00007fc1286ed000      4K rw---   [ anon ]
00007ffc7bc10000    132K rw---   [ stack ]
00007ffc7bd6d000      8K r-x--   [ anon ]
00007ffc7bd6f000      8K r----   [ anon ]
ffffffffff600000      4K r-x--   [ anon ]
 total           106616K
```

**Comment by kokoko3k** [comment]
Since fmlock is working fine, this issue should be closed.
Please, file a bug versus gopreload:
https://github.com/kokoko3k/gopreload
